### ISSUE TITLE
Action "Answer a question" is not a recognized action

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/action_server#29]
Probably not yet in the grammar

**Comment by MatthijsBurgh** [comment]
@LoyVanBeek, which questions can be expected?

**Comment by rokusottervanger** [comment]
@MatthijsBurgh take a look at the commands generated using the TC's command generator: tue-robotics/tue_robocup#329. We'll make sure we check these off.

**Comment by rokusottervanger** [comment]
BTW, this issue was solved in tue-robotics/tue_robocup@59893e0db5abd7b3329cab8c50616b6faa83cad8
