### ISSUE TITLE
SIMTEST 1306_1 Fix missing information statemachine

### ISSUE THREAD

**Issue by MaxBaeten** [tue-robotics/action_server#33]
------------------------------------------------------------------------
DATE: 13-06-17
TRY: 1
CMD: take the food to me follow robert to the trashbin and take me to the trashbin from the nightstand
BUG: Amigo asks after a command with missing info, where would you like me to get it but then does not continue
RESOLVE:- Fix missing information statemachine, 
------------------------------------------------------------------------

T[{actions : <A1>}] -> C[A1]
T[{actions : <A1, A2>}] -> C[A1] and C[A2]
T[..
[INFO] [1497290381.834596]: Example: [1;44m'put the salt from the dinner_table'[0m
[INFO] [1497290387.354203]: Robot heard [1;42m'take the food to me follow robert to the trashbin and take me to the trashbin from the nightstand'[0m {u'actions': [{u'action': u'bring', u'object': {u'type': u'food'}, u'target-location': {u'type': u'person', u'id': u'operator'}}, {u'action': u'follow', u'location-to': {u'id': u'trashbin'}, u'target': {u'id': u'robert'}}, {u'action': u'follow', u'location-to': {u'id': u'trashbin'}, u'location-from': {u'id': u'nightstand'}, u'target': {u'id': u'operator'}}]}
[INFO] [1497290387.354466]: [1;32m'I heard take the food to me follow robert to the trashbin and take me to the trashbin from the nightstand, is this correct?'[0m
[INFO] [1497290396.479000]: Question: , grammar: T -> yes | no
[INFO] [1497290396.479358]: Example: [1;44m'yes'[0m
[INFO] [1497290401.563872]: Robot heard [1;42m'yes'[0m None
actions[0].source-location
[INFO] [1497290401.648991]: [1;32m'Moving to the meeting point.'[0m
[INFO] [1497290402.595621]: State machine starting in initial state 'START_ANALYSIS' with userdata: 
	[]
[INFO] [1497290402.682886]: State machine transitioning 'START_ANALYSIS':'done'-->'NAVIGATE'
[INFO] [1497290402.683176]: State machine starting in initial state 'GET_PLAN' with userdata: 
	[]
[INFO] [1497290402.834242]: [1;32m'Getting there!'[0m
[INFO] [1497290403.754127]: State machine transitioning 'GET_PLAN':'goal_ok'-->'EXECUTE_PLAN'
[INFO] [1497290403.854899]: State machine terminating 'EXECUTE_PLAN':'succeeded':'arrived'
[INFO] [1497290403.855150]: State machine transitioning 'NAVIGATE':'arrived'-->'STOP_ANALYSIS_SUCCEED'
[INFO] [1497290403.935635]: State machine terminating 'STOP_ANALYSIS_SUCCEED':'done':'arrived'
[INFO] [1497290403.936692]: [1;32m' I don't have enough information to perform that task. Where would you like me to get it? '[0m
[INFO] [1497290412.870619]: Question: , grammar: T -> amigo
[INFO] [1497290412.871023]: Example: [1;44m'amigo'[0m
[INFO] [1497290417.985573]: Robot heard [1;42m'amigo'[0m None
[INFO] [1497290417.985847]: [1;32m'What can I do for you?'[0m
[INFO] [1497290420.800225]: Question: , grammar: 
T[{actions : <A1>}] -> C[A1]
T[{actions : <A1, A2>}] -> C[A1] and C[A2]

**Comment by rokusottervanger** [comment]
Does this mean the conversation after asking for the missing info?

**Comment by MaxBaeten** [comment]
Yes. Now it says: _I don't have enough information to perform that task. Where would you like me to get it?_ but then does not use the information but hears amigo and starts over.

**Comment by MaxBaeten** [comment]
closing all GPSR AND EGPRS issues!
